maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CW, 255)
basic.pause(100)
maqueen.motor_run(maqueen.Motors.ALL, maqueen.Dir.CCW, 220)
basic.pause(100)
maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, 128)
basic.pause(100)
maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CW, 128)
basic.pause(100)